### ISSUE TITLE
[Bug]: Typo in `README` doc for `KUBECONFIG`

### ISSUE THREAD

**Issue by karuppiah7890** [kube-ns-suspender/kube-ns-suspender#121]
### Version

9f886ab6ba12cd4fb252b49c05ed451500faf890

### What happened?

There's a bug (typo) in the development flow documentation - https://github.com/kube-ns-suspender/kube-ns-suspender?tab=readme-ov-file#development-flow

It says `KUBE_CONFIG` but it should be `KUBECONFIG`

### Anything else?

I can raise a PR to fix this and also fix any other issue I notice in the development flow and the corresponding docs

**Comment by eze-kiel** [comment]
hi @karuppiah7890, thanks for reporting the typo!
